# Generated by Django 5.0.1 on 2024-02-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_tittle_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='date_end',
            field=models.DateField(default='2024-01-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='date_start',
            field=models.DateField(default='2024-01-12'),
            preserve_default=False,
        ),
    ]
